import Head from "next/head";
import Header from "./components/Header";

export default function Home() {

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <h1>Blog del cigarrillo y la nicotina</h1>
        <p>El cigarrillo es un producto de consumo que contiene nicotina, una sustancia altamente adictiva. La adiccion al tabaco afecta a millones de peronas en todo el Mundo, causando graves problemas en la salud del individuo.</p>
      </main>
    </>
  );
}
